### ISSUE TITLE
Selecting multiple properties

### ISSUE THREAD

**Issue by retr0h** [pacifica/python-jsonpath2#52]
### jsonpath2 version

0.4.4

### Platform Details

macOS 10.15.6

### Scenario:

Select multiple items

### Steps to Reproduce:

```
import jsonpath2

d = {
    "a":1,
    "b":2,
    "c":3,
    "d":4,
    "e":5
}
    
_filter = '$.[a,b]'
jsonpath2.Path.parse_str(_filter)
match_data = [m.current_value
for m in p.match(d)]
print(match_data)
```

The above works on [jsonpath.com](http://jsonpath.com/)

Ultimately I'm trying to do something more complex and have a larger data set, where I would want to select 'image', 'name' below and $.concat(), onto a single line per item, but I can't even get the above to work.

```
components:
  - image: xxx:c910e45d
     name: generate-cluster-layout
  - image: xxx:c910e45d
     name: generate-ssh-key
  - image: xxx:c910e45d
     name: log-forwarder
```

### Expected Result:

```
[1,2]
```

### Actual Result:

```
ValueError: line 1:2 extraneous input '[' expecting {'*', ID}
```
